services:
  - type: web
    name: bohemia-tts-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    region: oregon
    pythonVersion: 3.10.13
